name: Build

on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - master

jobs:
  build:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Check with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: check

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        env:
          ORG_GRADLE_PROJECT_CURSE_TOKEN: ${{ secrets.CURSE_TOKEN }}
          ORG_GRADLE_PROJECT_MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY_RING_FILE }}
        with:
          arguments: build
