name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check with Gradle
        run: ./gradlew check

      - name: Publish new Version
        env:
          ORG_GRADLE_PROJECT_CURSE_TOKEN: ${{ secrets.CURSE_TOKEN }}
          ORG_GRADLE_PROJECT_MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY_RING_FILE }}
        run: ./gradlew publish -Pmod_version=${{ github.ref_name }}

      - name: Set variables
        run: |
          MINECRAFT_VER=$(grep -oP '(?<=minecraft_version\=).*' gradle.properties)
          echo "MINECRAFT_VER=$MINECRAFT_VER" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./repo/io/github/pixel-mk/pixelmkmenu-${{ env.MINECRAFT_VER }}/${{ github.ref_name }}/pixelmkmenu-${{ env.MINECRAFT_VER }}-${{ github.ref_name }}*.jar
